### ISSUE TITLE
Add support for sphinx versions prior to 1.6

### ISSUE THREAD

**Issue by pri22296** [fossasia/sphinx_fossasia_theme#2]
## Description

Currently setup.py uses `sphinx.html_themes` entry point. It was introduced with sphinx 1.6. Before that `sphinx_themes` entry point was used but has been deprecated now. Thus our theme fails to work with the sphinx version < 1.6. setup.py should be modified to handle this case depending on sphinx version.

See https://github.com/fossasia/sphinx_fossasia_theme/pull/1#pullrequestreview-48401686 for details

**Comment by imujjwal96** [comment]
Please describe the issue here as well, there is no need to make someone open another link to understand this issue.

**Comment by pri22296** [comment]
Updated the description
