### ISSUE TITLE
Image are not rendering properly

### ISSUE THREAD

**Issue by poonai** [fossasia/sphinx_fossasia_theme#20]
![issue](https://user-images.githubusercontent.com/10010900/28404111-945e35a0-6d45-11e7-8514-f9379d74ce07.png)
http://yaydoc.herokuapp.com/preview/rbalajis25@gmail.com/12602299-7367-470c-8da6-eb0fb6acc06f_preview/
customize the css to render the image properly

**Comment by imujjwal96** [comment]
The fix has been merged. It's not yet released. Closing this.

**Comment by poonai** [comment]
@imujjwal96 please release the fix. it'll help to generate documentation for `open-event-orga-app`
