### ISSUE TITLE
Add a base templating HTML structure

### ISSUE THREAD

**Issue by imujjwal96** [fossasia/sphinx_fossasia_theme#4]
### Description
Add a base templating HTML structure for the theme similar to Sphinx's built in base theme. 
Without inheriting any theme and using structure same as that used by the base Sphinx theme will be a good learning curve and will help to extend it as per our needs

**Update**: After discussion, it is decided that we will instead inherit from the `basic` theme. As @pri22296 pointed out, From the sphinx docs:

> The inherit setting gives the name of a “base theme”, or none. The base theme will be used to locate missing templates (most themes will not have to supply most templates if they use basic as the base theme), its options will be inherited, and all of its static files will be used as well.

Parent issue: https://github.com/fossasia/sphinx_fossasia_theme/issues/3

**Comment by pri22296** [comment]
@imujjwal96 Are you sure you wanna go the `inherit = none` way? Every custom theme seems to inherits from basic. Even the built-in themes inherit from basic.

**Comment by imujjwal96** [comment]
I'm open to suggestions. it's just about the feasibility. I've also been doing some research about that. If things don't seem to work, I'll go with inheriting the base.

**Comment by imujjwal96** [comment]
Ok. So let's work with inheriting the `basic` theme then.

**Comment by pri22296** [comment]
It's just that I couldn't find any other theme which doesn't inherits from basic. 
From the sphinx docs:

> The inherit setting gives the name of a “base theme”, or none. The base theme will be used to locate missing templates (most themes will not have to supply most templates if they use basic as the base theme), its options will be inherited, and all of its static files will be used as well.

It's seem inheriting from basic just helps us avoid doing redundant stuff

**Comment by imujjwal96** [comment]
Close this then?

**Comment by pri22296** [comment]
Yep
